### ISSUE TITLE
como faz pra juntar tudo?

### ISSUE THREAD

**Issue by tudoesom** [lepsi28/arduinoday2018#1]
junt tudo e joga fora essa porra caralho.

**Comment by portellapedro** [comment]
Silence is Gold

**Comment by portellapedro** [comment]
![napkinh-visual-grammar](https://user-images.githubusercontent.com/10197081/39095006-a8359ca0-460f-11e8-9c0a-196a41079b5f.jpg)

**Comment by tudoesom** [comment]
Email

Em 22 de abr de 2018 9:29 AM, "Pedro Portella" <notifications@github.com>
escreveu:

**Comment by portellapedro** [comment]
[TT Preamp.pdf](https://github.com/lepsi28/arduinoday2018/files/1935584/TT.Preamp.pdf)

**Comment by portellapedro** [comment]
junta tudo e joga fora
